---

- name: Enable CloudWatch monitoring and alarms
  hosts: 127.0.0.1
  connection: local
  user: root
  gather_facts: false

  roles:
    - ansible-cloudwatch-metrics
    - ansible-cloudwatch-alarms
